import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
// import { useRouter } from 'next/router'
import AppLayout from '../components/AppLayout'

export default function Home() {
  // const router = useRouter()
  // console.log(router)
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Devter</a>
        </h1>
      </AppLayout>

    </>
  )
}