import { useEffect, useState } from 'react'
import Head from 'next/head'

import AppLayout from 'components/AppLayout'
import Button from 'components/Button'
import GitHub from 'components/Icons/github'
import Logo from 'components/Icons/logo'

import styles from 'styles/Home.module.scss'
import { colors } from 'styles/theme'

import { listenAuthStateChanged, loginWithGitHub } from 'firebaseSesion/client'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const [user, setUser] = useState(null)

  useEffect(() => {
    listenAuthStateChanged(setUser)
  }, [])

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGitHub()
      .then(setUser)
      .catch((err) => {
        console.log(err)
      })
  }

  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <Logo width='100' />
          <h1 className={styles.title}>Devter</h1>
          <h2>
            Talk about development
            <br />
            with developers 👨🏻‍💻 👩🏻‍💻
          </h2>
          <div>
            {user === null ? (
              <Button onClick={handleClick}>
                <GitHub />
                Login with GitHub
              </Button>
            ) : <span>Loading...</span>}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        img {
          width: 120px;
        }

        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }

        div {
          margin-top: 16px;
        }

        h1 {
          color: ${colors.primary};
          font-weight: 800;
          font-size: 32px;
          margin-bottom: 16px;
          text-align: center;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 21px;
          margin: 0;
        }
        span{
          font-weight: bold;
          color: ${colors.primary};
        }
      `}</style>
    </>
  )
}
